### PR TITLE
ci: replace travis with github actions

### PR DESCRIPTION
**Pull request by strophy**
It is not possible to deploy this repo because Travis CI is no longer available. This PR replaces Travis with Github Actions.

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
👍

**Comment by UdjinM6** [comment]
(someone with admin permissions should also go to Settings -> Branches -> Branch protection rules -> Edit (for `master`) -> Require status checks to pass before merging -> drop travis from the list ;) )

**Comment by nmarley** [comment]
@QuantumExplorer Can you help w/disabling Travis? ☝️

**Comment by shumkov** [comment]
@nmarley done

**Pull request merged**
