### PR TITLE
quick rebrand w/new logo and CSS

### PR DESCRIPTION
**Pull request by nmarley**

### CODE REVIEW

**Comment by snogcel** [comment]
I performed some testing on this today and found that the design changes look fine, however the functionality of the tool is currently broken. 

image

image

The root cause is the removal of the "step_two" id from index.html: https://github.com/dashevo/proposal-generator/pull/34/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL108

This ID is referenced within index.js here: https://github.com/dashevo/proposal-generator/blob/rebrand/js/index.js#L105

**Comment by iamsuba** [comment]
i just pushed a small fix to the create proposal link button

**Review by iamsuba — COMMENTED** [review]
just pushed an update

**Review by iamsuba — APPROVED** [review]
just pushed an update

**Comment by snogcel** [comment]
Sorry this took me so long to review! I ran some testing on this today and it looks like those fixes solved the problem - I was able to successfully create a proposal today on Testnet:

image

**Pull request closed without merging**
